sudo: false
language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  env: CHANNEL=conda-forge

before_install:
  - travis_retry wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda install --yes numpy scipy pip nose
  - if [ -n "$CHANNEL" ]; then conda config --add channels $CHANNEL; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then conda install --yes pyparsing biopython unittest2; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.5" ]]; then conda install --yes pyparsing biopython; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.6" ]]; then conda install --yes pyparsing biopython; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.7" ]]; then conda install --yes pyparsing biopython; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.8" ]]; then conda install --yes pyparsing biopython; fi
  - if [[ -n "$CHANNEL" ]]; then conda install --yes prody; else python setup.py build install; fi
script:
  - cd docs; nosetests prody -a '!slow'
